version: 2
updates:
  - package-ecosystem: npm
    directory: "/"
    open-pull-requests-limit: 3
    schedule:
      interval: daily
    commit-message:
      prefix: fix
      prefix-development: chore
      include: scope
