version: 2.1

orbs:
  node: circleci/node@4.5.1

executors:
  default_executor:
    working_directory: ~/jsonapi-transformers
    docker:
      - image: cimg/node:12.22.3
        auth:
          username: $DOCKER_USERNAME
          password: $DOCKER_PASSWORD

jobs:
  build_and_test:
    executor: default_executor
    steps:
      - checkout
      - node/install-packages
      - run:
          name: Run linters
          command: npm run lint
      - run:
          name: Run unit tests
          command: npm run test
      - run:
          name: Rebuild the release directory (lib/)
          command: npm run build
      - run:
          name: Check that there are no uncommitted changes
          command: if output=$(git status --porcelain) && [ -z "$output" ]; then exit 0; else exit 1; fi;

workflows:
  test:
    jobs:
      - build_and_test
