version: 2.1

orbs:
  node: circleci/node@4.5.1
  sonarcloud: sonarsource/sonarcloud@1.0.3

executors:
  default_executor:
    working_directory: ~/jsonapi-transformers
    docker:
      - image: cimg/node:18.4.0
        auth:
          username: $DOCKER_USERNAME
          password: $DOCKER_PASSWORD

jobs:
  build_and_test:
    executor: default_executor
    steps:
      - add_ssh_keys:
          fingerprints:
            - "04:e1:85:d2:0f:ac:cc:35:da:f6:93:b4:3f:9a:68:15" # 'deploykey_junglebarry_jsonapitransformers_circleci_ed25519_2023_01_06'
      - checkout
      - node/install-packages
      - run:
          name: Define environment variable with lastest commit's message
          command: |
            echo 'export COMMIT_MESSAGE=$(git log -1 --pretty=format:"%s")' >> $BASH_ENV
            source $BASH_ENV
      - run:
          name: Lint commit message
          command: echo "$COMMIT_MESSAGE" | npx commitlint
      - run:
          name: Run linters
          command: npm run lint
      - run:
          name: Ensure the JSON:API examples are validated against the JSON:API schema
          command: npm run validate_jsonapi_examples
      - run:
          name: Run unit tests
          command: npm run test
      - store_artifacts:
          path: coverage
      - sonarcloud/scan
      - run:
          name: Rebuild the release directory (lib/)
          command: npm run build
      - run:
          name: Semantic Release
          command: npx semantic-release

workflows:
  test:
    jobs:
      - build_and_test:
          context:
            - dockerhub/junglebarry
            - sonarcloud/junglebarry
